// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.14.0
// source: internal/storage/pb/storage.proto

package storagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChunkData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// upload_id 上传会话 ID（仅第一个包携带元信息，后续包只带 data）。
	UploadId string `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	// index 分片序号。
	Index int32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// data 分片原始字节。
	Data          []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkData) Reset() {
	*x = ChunkData{}
	mi := &file_internal_storage_pb_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkData) ProtoMessage() {}

func (x *ChunkData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_storage_pb_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkData.ProtoReflect.Descriptor instead.
func (*ChunkData) Descriptor() ([]byte, []int) {
	return file_internal_storage_pb_storage_proto_rawDescGZIP(), []int{0}
}

func (x *ChunkData) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *ChunkData) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChunkData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ChunkResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chunk_hash 分片内容 SHA256 哈希（hex）。
	ChunkHash string `protobuf:"bytes,1,opt,name=chunk_hash,json=chunkHash,proto3" json:"chunk_hash,omitempty"`
	// size 分片字节大小。
	Size int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// storage_id 实际落盘的存储节点标识。
	StorageId string `protobuf:"bytes,3,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	// reused 是否命中已存在分片（去重）。
	Reused        bool `protobuf:"varint,4,opt,name=reused,proto3" json:"reused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkResult) Reset() {
	*x = ChunkResult{}
	mi := &file_internal_storage_pb_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkResult) ProtoMessage() {}

func (x *ChunkResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_storage_pb_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkResult.ProtoReflect.Descriptor instead.
func (*ChunkResult) Descriptor() ([]byte, []int) {
	return file_internal_storage_pb_storage_proto_rawDescGZIP(), []int{1}
}

func (x *ChunkResult) GetChunkHash() string {
	if x != nil {
		return x.ChunkHash
	}
	return ""
}

func (x *ChunkResult) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ChunkResult) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

func (x *ChunkResult) GetReused() bool {
	if x != nil {
		return x.Reused
	}
	return false
}

type ChunkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// storage_id 目标存储节点（客户端用于校验）。
	StorageId string `protobuf:"bytes,1,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	// chunk_hash 分片内容哈希。
	ChunkHash     string `protobuf:"bytes,2,opt,name=chunk_hash,json=chunkHash,proto3" json:"chunk_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkRequest) Reset() {
	*x = ChunkRequest{}
	mi := &file_internal_storage_pb_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkRequest) ProtoMessage() {}

func (x *ChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_storage_pb_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkRequest.ProtoReflect.Descriptor instead.
func (*ChunkRequest) Descriptor() ([]byte, []int) {
	return file_internal_storage_pb_storage_proto_rawDescGZIP(), []int{2}
}

func (x *ChunkRequest) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

func (x *ChunkRequest) GetChunkHash() string {
	if x != nil {
		return x.ChunkHash
	}
	return ""
}

type ChunkDataMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// data 分片原始字节。
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// total_size 总分片大小。
	TotalSize     int64 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkDataMsg) Reset() {
	*x = ChunkDataMsg{}
	mi := &file_internal_storage_pb_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkDataMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkDataMsg) ProtoMessage() {}

func (x *ChunkDataMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_storage_pb_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkDataMsg.ProtoReflect.Descriptor instead.
func (*ChunkDataMsg) Descriptor() ([]byte, []int) {
	return file_internal_storage_pb_storage_proto_rawDescGZIP(), []int{3}
}

func (x *ChunkDataMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChunkDataMsg) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type DeleteResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResult) Reset() {
	*x = DeleteResult{}
	mi := &file_internal_storage_pb_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResult) ProtoMessage() {}

func (x *DeleteResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_storage_pb_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResult.ProtoReflect.Descriptor instead.
func (*DeleteResult) Descriptor() ([]byte, []int) {
	return file_internal_storage_pb_storage_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ExistResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistResult) Reset() {
	*x = ExistResult{}
	mi := &file_internal_storage_pb_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistResult) ProtoMessage() {}

func (x *ExistResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_storage_pb_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistResult.ProtoReflect.Descriptor instead.
func (*ExistResult) Descriptor() ([]byte, []int) {
	return file_internal_storage_pb_storage_proto_rawDescGZIP(), []int{5}
}

func (x *ExistResult) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_internal_storage_pb_storage_proto protoreflect.FileDescriptor

const file_internal_storage_pb_storage_proto_rawDesc = "" +
	"\n" +
	"!internal/storage/pb/storage.proto\x12\tstoragepb\"R\n" +
	"\tChunkData\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"w\n" +
	"\vChunkResult\x12\x1d\n" +
	"\n" +
	"chunk_hash\x18\x01 \x01(\tR\tchunkHash\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1d\n" +
	"\n" +
	"storage_id\x18\x03 \x01(\tR\tstorageId\x12\x16\n" +
	"\x06reused\x18\x04 \x01(\bR\x06reused\"L\n" +
	"\fChunkRequest\x12\x1d\n" +
	"\n" +
	"storage_id\x18\x01 \x01(\tR\tstorageId\x12\x1d\n" +
	"\n" +
	"chunk_hash\x18\x02 \x01(\tR\tchunkHash\"A\n" +
	"\fChunkDataMsg\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x03R\ttotalSize\"\x1e\n" +
	"\fDeleteResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"%\n" +
	"\vExistResult\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists2\x8c\x02\n" +
	"\vStorageNode\x12;\n" +
	"\tSaveChunk\x12\x14.storagepb.ChunkData\x1a\x16.storagepb.ChunkResult(\x01\x12?\n" +
	"\tReadChunk\x12\x17.storagepb.ChunkRequest\x1a\x17.storagepb.ChunkDataMsg0\x01\x12?\n" +
	"\vDeleteChunk\x12\x17.storagepb.ChunkRequest\x1a\x17.storagepb.DeleteResult\x12>\n" +
	"\vChunkExists\x12\x17.storagepb.ChunkRequest\x1a\x16.storagepb.ExistResultB,Z*webdownld_go/internal/storage/pb;storagepbb\x06proto3"

var (
	file_internal_storage_pb_storage_proto_rawDescOnce sync.Once
	file_internal_storage_pb_storage_proto_rawDescData []byte
)

func file_internal_storage_pb_storage_proto_rawDescGZIP() []byte {
	file_internal_storage_pb_storage_proto_rawDescOnce.Do(func() {
		file_internal_storage_pb_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_storage_pb_storage_proto_rawDesc), len(file_internal_storage_pb_storage_proto_rawDesc)))
	})
	return file_internal_storage_pb_storage_proto_rawDescData
}

var file_internal_storage_pb_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_storage_pb_storage_proto_goTypes = []any{
	(*ChunkData)(nil),    // 0: storagepb.ChunkData
	(*ChunkResult)(nil),  // 1: storagepb.ChunkResult
	(*ChunkRequest)(nil), // 2: storagepb.ChunkRequest
	(*ChunkDataMsg)(nil), // 3: storagepb.ChunkDataMsg
	(*DeleteResult)(nil), // 4: storagepb.DeleteResult
	(*ExistResult)(nil),  // 5: storagepb.ExistResult
}
var file_internal_storage_pb_storage_proto_depIdxs = []int32{
	0, // 0: storagepb.StorageNode.SaveChunk:input_type -> storagepb.ChunkData
	2, // 1: storagepb.StorageNode.ReadChunk:input_type -> storagepb.ChunkRequest
	2, // 2: storagepb.StorageNode.DeleteChunk:input_type -> storagepb.ChunkRequest
	2, // 3: storagepb.StorageNode.ChunkExists:input_type -> storagepb.ChunkRequest
	1, // 4: storagepb.StorageNode.SaveChunk:output_type -> storagepb.ChunkResult
	3, // 5: storagepb.StorageNode.ReadChunk:output_type -> storagepb.ChunkDataMsg
	4, // 6: storagepb.StorageNode.DeleteChunk:output_type -> storagepb.DeleteResult
	5, // 7: storagepb.StorageNode.ChunkExists:output_type -> storagepb.ExistResult
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_storage_pb_storage_proto_init() }
func file_internal_storage_pb_storage_proto_init() {
	if File_internal_storage_pb_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_storage_pb_storage_proto_rawDesc), len(file_internal_storage_pb_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_storage_pb_storage_proto_goTypes,
		DependencyIndexes: file_internal_storage_pb_storage_proto_depIdxs,
		MessageInfos:      file_internal_storage_pb_storage_proto_msgTypes,
	}.Build()
	File_internal_storage_pb_storage_proto = out.File
	file_internal_storage_pb_storage_proto_goTypes = nil
	file_internal_storage_pb_storage_proto_depIdxs = nil
}
