// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.14.0
// source: internal/storage/pb/storage.proto

package storagepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageNode_SaveChunk_FullMethodName   = "/storagepb.StorageNode/SaveChunk"
	StorageNode_ReadChunk_FullMethodName   = "/storagepb.StorageNode/ReadChunk"
	StorageNode_DeleteChunk_FullMethodName = "/storagepb.StorageNode/DeleteChunk"
	StorageNode_ChunkExists_FullMethodName = "/storagepb.StorageNode/ChunkExists"
)

// StorageNodeClient is the client API for StorageNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StorageNode 是存储节点的 gRPC 接口，负责分片文件的落盘与读取。
type StorageNodeClient interface {
	// SaveChunk 流式上传分片数据到存储节点，返回保存结果。
	SaveChunk(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ChunkData, ChunkResult], error)
	// ReadChunk 流式读取分片数据。
	ReadChunk(ctx context.Context, in *ChunkRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChunkDataMsg], error)
	// DeleteChunk 删除指定分片。
	DeleteChunk(ctx context.Context, in *ChunkRequest, opts ...grpc.CallOption) (*DeleteResult, error)
	// ChunkExists 检查分片是否存在（用于去重预判）。
	ChunkExists(ctx context.Context, in *ChunkRequest, opts ...grpc.CallOption) (*ExistResult, error)
}

type storageNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageNodeClient(cc grpc.ClientConnInterface) StorageNodeClient {
	return &storageNodeClient{cc}
}

func (c *storageNodeClient) SaveChunk(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ChunkData, ChunkResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageNode_ServiceDesc.Streams[0], StorageNode_SaveChunk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChunkData, ChunkResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageNode_SaveChunkClient = grpc.ClientStreamingClient[ChunkData, ChunkResult]

func (c *storageNodeClient) ReadChunk(ctx context.Context, in *ChunkRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChunkDataMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageNode_ServiceDesc.Streams[1], StorageNode_ReadChunk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChunkRequest, ChunkDataMsg]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageNode_ReadChunkClient = grpc.ServerStreamingClient[ChunkDataMsg]

func (c *storageNodeClient) DeleteChunk(ctx context.Context, in *ChunkRequest, opts ...grpc.CallOption) (*DeleteResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResult)
	err := c.cc.Invoke(ctx, StorageNode_DeleteChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageNodeClient) ChunkExists(ctx context.Context, in *ChunkRequest, opts ...grpc.CallOption) (*ExistResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExistResult)
	err := c.cc.Invoke(ctx, StorageNode_ChunkExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageNodeServer is the server API for StorageNode service.
// All implementations must embed UnimplementedStorageNodeServer
// for forward compatibility.
//
// StorageNode 是存储节点的 gRPC 接口，负责分片文件的落盘与读取。
type StorageNodeServer interface {
	// SaveChunk 流式上传分片数据到存储节点，返回保存结果。
	SaveChunk(grpc.ClientStreamingServer[ChunkData, ChunkResult]) error
	// ReadChunk 流式读取分片数据。
	ReadChunk(*ChunkRequest, grpc.ServerStreamingServer[ChunkDataMsg]) error
	// DeleteChunk 删除指定分片。
	DeleteChunk(context.Context, *ChunkRequest) (*DeleteResult, error)
	// ChunkExists 检查分片是否存在（用于去重预判）。
	ChunkExists(context.Context, *ChunkRequest) (*ExistResult, error)
	mustEmbedUnimplementedStorageNodeServer()
}

// UnimplementedStorageNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageNodeServer struct{}

func (UnimplementedStorageNodeServer) SaveChunk(grpc.ClientStreamingServer[ChunkData, ChunkResult]) error {
	return status.Error(codes.Unimplemented, "method SaveChunk not implemented")
}
func (UnimplementedStorageNodeServer) ReadChunk(*ChunkRequest, grpc.ServerStreamingServer[ChunkDataMsg]) error {
	return status.Error(codes.Unimplemented, "method ReadChunk not implemented")
}
func (UnimplementedStorageNodeServer) DeleteChunk(context.Context, *ChunkRequest) (*DeleteResult, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteChunk not implemented")
}
func (UnimplementedStorageNodeServer) ChunkExists(context.Context, *ChunkRequest) (*ExistResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ChunkExists not implemented")
}
func (UnimplementedStorageNodeServer) mustEmbedUnimplementedStorageNodeServer() {}
func (UnimplementedStorageNodeServer) testEmbeddedByValue()                     {}

// UnsafeStorageNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageNodeServer will
// result in compilation errors.
type UnsafeStorageNodeServer interface {
	mustEmbedUnimplementedStorageNodeServer()
}

func RegisterStorageNodeServer(s grpc.ServiceRegistrar, srv StorageNodeServer) {
	// If the following call panics, it indicates UnimplementedStorageNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageNode_ServiceDesc, srv)
}

func _StorageNode_SaveChunk_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StorageNodeServer).SaveChunk(&grpc.GenericServerStream[ChunkData, ChunkResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageNode_SaveChunkServer = grpc.ClientStreamingServer[ChunkData, ChunkResult]

func _StorageNode_ReadChunk_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChunkRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageNodeServer).ReadChunk(m, &grpc.GenericServerStream[ChunkRequest, ChunkDataMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageNode_ReadChunkServer = grpc.ServerStreamingServer[ChunkDataMsg]

func _StorageNode_DeleteChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServer).DeleteChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNode_DeleteChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServer).DeleteChunk(ctx, req.(*ChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageNode_ChunkExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServer).ChunkExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNode_ChunkExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServer).ChunkExists(ctx, req.(*ChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageNode_ServiceDesc is the grpc.ServiceDesc for StorageNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storagepb.StorageNode",
	HandlerType: (*StorageNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteChunk",
			Handler:    _StorageNode_DeleteChunk_Handler,
		},
		{
			MethodName: "ChunkExists",
			Handler:    _StorageNode_ChunkExists_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SaveChunk",
			Handler:       _StorageNode_SaveChunk_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ReadChunk",
			Handler:       _StorageNode_ReadChunk_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/storage/pb/storage.proto",
}
